# Generated by Django 5.0.2 on 2024-04-15 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='County',
            fields=[
                ('county_id', models.AutoField(primary_key=True, serialize=False)),
                ('county_name', models.CharField(help_text='Enter a valid County Name', max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('specialization_id', models.AutoField(primary_key=True, serialize=False)),
                ('specialization_name', models.CharField(help_text='Enter a valid Specialization Name', max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TechCompany',
            fields=[
                ('tech_company_id', models.AutoField(primary_key=True, serialize=False)),
                ('tech_company_name', models.CharField(help_text='Enter a valid Company Name', max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Constituency',
            fields=[
                ('constituency_id', models.AutoField(primary_key=True, serialize=False)),
                ('constituency_name', models.CharField(help_text='Enter a valid Constituency Name', max_length=255, unique=True)),
                ('county_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='connect.county')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(help_text='Enter a valid first name', max_length=200)),
                ('last_name', models.CharField(help_text='Enter a valid last name', max_length=200)),
                ('email_address', models.EmailField(help_text='Enter a valid email address', max_length=200, unique=True)),
                ('password_hash', models.CharField(help_text='Enter a valid password', max_length=128)),
                ('specialization_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='connect.specialization')),
            ],
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('ward_id', models.AutoField(primary_key=True, serialize=False)),
                ('ward_name', models.CharField(help_text='Enter a valid Ward Name', max_length=255, unique=True)),
                ('constituency_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='connect.constituency')),
            ],
        ),
        migrations.CreateModel(
            name='SlotsAvailable',
            fields=[
                ('slots_available_id', models.AutoField(primary_key=True, serialize=False)),
                ('slot_count', models.PositiveIntegerField(help_text='Enter a valid Slot Number')),
                ('application_deadline', models.DateTimeField(help_text='Enter application deadline')),
                ('application_instructions', models.TextField(blank=True, help_text='Enter application instructions')),
                ('slots_filled', models.PositiveIntegerField(default=0)),
                ('specialization_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='connect.specialization')),
                ('tech_company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='connect.techcompany')),
                ('ward_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='connect.ward')),
            ],
        ),
    ]
